version: "3.1"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO-INITDB_ROOT_USERNAME=admin
      - MONGO-INITDB_ROOT_PASSWORD=pass
  mongodb-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://admin:pass@mongodb:27017/?authSource=admin"
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb
